name: web.dart
version: 0.1.0
dependencies:
  shelf: ^0.6.8
  shelf_auth: ^0.7.4
  shelf_oauth: ^0.8.2
  shelf_simple_session: ^0.1.3
  shelf_auth_session: ^0.4.12
  shelf_static: ^0.2.4
  uri_template: ^0.6.0
  yaml: ^2.1.12
  bwu_log: ^0.1.2