name: webart
version: 0.3.0
description: A relax, simple lightweight non-sync web framework for dart, based on shelf.Just write down your art.
homepage: https://gitlab.com/thislight/web.dart
author: thisLight <l1589002388@gmail.com>
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  shelf: "^0.7.3"
  uri_template: "^0.6.0"
  logging: "^0.11.3"
dev_dependencies:
  test: "^0.12.0"
  http: "^0.11.3"
