name: webart
version: 0.2.0-alpha.8
description: A lightweight web framework for dart
homepage: https://gitlab.com/thislight/web.dart
author: thisLight <l1589002388@gmail.com>
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  shelf: "^0.7.1"
  uri_template: "^0.6.0"
  yaml: "^2.1.12"
  bwu_log: "^0.1.2"
  logging: "^0.11.3"
dev_dependencies:
  test: "^0.12.30"
